### ISSUE TITLE
Quellenverzeichnis oder Fußnoten?

### ISSUE THREAD

**Issue by x4121** [x4121/MobileNetzeDocu#1]
Was meint ihr zu Quellen/Zitaten etc.:
Brauchen wir ein Quellenverzeichnis oder reichen für die wenigen Quellen auch vereinzelte Fußnoten?

**Comment by christiang830** [comment]
Hm ka. wenn paar Quellen zusammenkommen kann man schon ne Bib machen denk ich. Ich brauch bei meinem Teil jefenfalls keine, hab nur Qt als Fußnote angegeben

**Comment by TheBoegl** [comment]
👍
